# Generated by Django 4.1.2 on 2022-11-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Aartical',
            field=models.CharField(max_length=1000),
        ),
    ]
