# Generated by Django 4.1.3 on 2022-11-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_comments_remove_dislike_comment_remove_dislike_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='enroll.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
