# Generated by Django 4.1.3 on 2022-11-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='enroll.post')),
                ('likeusers', models.ManyToManyField(to='enroll.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
