# Generated by Django 4.1.3 on 2022-11-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_post_postlikes_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='likeusers',
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='likepost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='enroll.blog'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
